server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: empleado-service
          uri: lb://empleado-service
          predicates:
            - Path=/empleado/**
        - id: archivo-service
          uri: lb://archivo-service
          predicates:
            - Path=/upload/**
        - id: bPuntualidad-service
          uri: lb://bPuntualidad-service
          predicates:
            - Path=/bonoPuntualidad/**
        - id: bTiempo-service
          uri: lb://bTiempo-service
          predicates:
            - Path=/bonoTiempo/**
        - id: dLey-service
          uri: lb://dLey-service
          predicates:
            - Path=/dLey/**
        - id: dRetiro-service
          uri: lb://dRetiro-service
          predicates:
            - Path=/dRetiro/**
        - id: dTardanza-service
          uri: lb://dTardanza-service
          predicates:
            - Path=/dTardanza/**
        - id: hExtra-service
          uri: lb://hExtra-service
          predicates:
            - Path=/hExtra/**
        - id: sueldoFijo-service
          uri: lb://sueldoFijo-service
          predicates:
            - Path=/sueldoFijo/**
        - id: calculo-service
          uri: lb://calculo-service
          predicates:
            - Path=/calculo/**
        - id: justificativo-service
          uri: lb://justificativo-service
          predicates:
            - Path=/justificativo/**